### ISSUE TITLE
启动后无法通过IP访问呢

### ISSUE THREAD

**Issue by wukailing112113** [xming521/WorkAggregation#23]
FLASK_APP = server.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder D:/codes/可视化/WorkAggregation
C:\Users\My\.conda\envs\py36\python.exe -m flask run 
 * Serving Flask app "server.py"
 * Environment: development
 * Debug mode: off
[20.0, 7000.0, 9000.0, 12500.0, 250000.0]

**Comment by fightyea** [comment]
解决了吗，这个是不是坏掉了
