### ISSUE TITLE
spider_main只给出了测试代码？

### ISSUE THREAD

**Issue by IcePaper** [xming521/WorkAggregation#4]
没有给出三个爬虫选项的完整代码？

**Comment by xming521** [comment]
```
p1 = SpiderProcess(queue, job, city, type=
dict_ parameter.get('type '),threads=threads)
```
这里的type参数可以控制爬取数据来源

**Comment by xming521** [comment]
> ```
> p1 = SpiderProcess(queue, job, city, type=
> dict_ parameter.get('type '),threads=threads)
> ```
> 这里的type参数可以控制爬取数据来源

@IcePaper

**Comment by IcePaper** [comment]
你好~我还想请问一下,在input_data.py文件中sql_2有个绝对路径C:/Users/Administrator/Desktop/process/job/
我想请问这个文件夹里面放的什么文件，是不是分别名为‘qcwy.csv','qlrc.csv','big.csv'的三个文件，但是在爬虫代码中所有的数据都写进了test.csv。
with open('data/test.csv', 'a+', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(
        ['provider', 'keyword', 'title', 'place', 'salary', 'experience', 'education', 'companytype',
         'industry', 'description'])

是不是数据存储这部分代码不完善需要自己补充？或者有什么别的方法让代码正确运行起来？
非常抱歉占用您的时间，但是如果您能回答的话万分感激！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xming521/WorkAggregation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 晚上6:19
收件人:&nbsp;"xming521/WorkAggregation"<WorkAggregation@noreply.github.com&gt;;
抄送:&nbsp;"倩哥在学习"<1641546473@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xming521/WorkAggregation] spider_main只给出了测试代码？ (#4)





  p1 = SpiderProcess(queue, job, city, type= dict_ parameter.get('type '),threads=threads)  
这里的type参数可以控制爬取数据来源
  
@IcePaper
