### ISSUE TITLE
兼容性太差！

### ISSUE THREAD

**Issue by gordonwalkedby** [xming521/WorkAggregation#8]

**Comment by gordonwalkedby** [comment]
环境： win10 py3.9.2 
新装的，然后升级了 pip
就没法正常工作
管理员运行 install_package.bat 
就下面这样

ERROR: Command errored out with exit status 1:
     command: 'c:\users\p1\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\p1\\AppData\\Local\\Temp\\pip-install-d8ibd7wf\\dukpy_5be5ed3c00d4409db6ec187068dbefc6\\setup.py'"'"'; file='"'"'C:\\Users\\p1\\AppData\\Local\\Temp\\pip-install-d8ibd7wf\\dukpy_5be5ed3c00d4409db6ec187068dbefc6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\p1\AppData\Local\Temp\pip-record-4jrr2k7h\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\p1\appdata\local\programs\python\python39\Include\dukpy'
         cwd: C:\Users\p1\AppData\Local\Temp\pip-install-d8ibd7wf\dukpy_5be5ed3c00d4409db6ec187068dbefc6\

server.py 直接运行就说 没有 flask （
你兼容性为什么这么差

**Comment by xming521** [comment]
谁让你用python3.9了....
